### ISSUE TITLE
Soft deprecation of dbGetPreparedQuery?

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RSQLite#100]
I got an error related to the deprecation of `dbGetPreparedQuery` when trying to use the `BatchJobs` package. There are [over 200 hits on GitHub](https://github.com/search?utf8=%E2%9C%93&q=dbGetPreparedQuery&type=Code&ref=searchresults) for `dbGetPreparedQuery` when using R as language filter. The removal of `dbGetPreparedQuery` might break many packages. On the other hand, the current CRAN version doesn't seem to support `dbBind` yet.

I think a soft deprecation where `dbGetPreparedQuery` still exists but gives a warning will be easier to handle by the downstream package maintainers.

**Comment by krlmlr** [comment]
Revisit after revdep check.

**Comment by richfitz** [comment]
Hi! I'm currently revising a [package](https://github.com/richfitz/storr) to meet a change in a downstream dependency (testthat) and would like to know if I should be hedging against this not being soft deprecated too.  Unfortunately I use it in a vignette so long workarounds are going to look a bit ugly.

Any idea on if soft deprecation is likely or what the timeline is for a CRAN release?

**Comment by krlmlr** [comment]
At least there'll be a warning, which won't look particularly nice in the vignette. Can you use dbWriteTable() for your example?

**Comment by hadley** [comment]
Soft dep seems reasonable. We can deprecate in the next version

**Comment by krlmlr** [comment]
Means we need to reimplement it using `dbBind()`.

**Comment by richfitz** [comment]
Brilliant, soft deprecation would be great.

The vignette example uses `dbGetPreparedQuery` to add raw data into a table.  `dbBind` will do the same, I'm waiting on that in the CRAN version and will swap it over once it's updated.

**Comment by krlmlr** [comment]
I think this would work just the same with dbWriteTable(), but I'd love to get your feedback on the upcoming compat implementation of dbGetPreparedQuery().

**Comment by richfitz** [comment]
I presume from the automated email about the upcoming RSQLite release that soft deprecation was decided against in the end?

**Comment by krlmlr** [comment]
@richfitz: Probably there's no way around soft deprecation, too many packages are using `dbGetPreparedQuery()`. Thanks for the nudge!
