### ISSUE TITLE
Cannot Support Chinese Characters

### ISSUE THREAD

**Issue by BruceZhaoR** [rstats-db/RSQLite#108]
## Here My code:

![1](https://cloud.githubusercontent.com/assets/8092534/10933790/f2932390-8315-11e5-9516-316aa31ae5a9.png)

## But in Cmd
I type `chcp 65001` ,change the encoding to UTF-8 , it worked.   

![2](https://cloud.githubusercontent.com/assets/8092534/10933813/292cfdae-8316-11e5-9cf3-5faa844f4fdb.png)
![3](https://cloud.githubusercontent.com/assets/8092534/10933823/3650798e-8316-11e5-8d5d-f8f6147ca929.png)

###  What should I do to slove this problem ? 

I have tried` stringi::stri_enc_set("UTF-8")`

>You are now working with stringi_1.0.1 (zh_CN.UTF-8; ICU4C 55.1 [bundle]; Unicode 7.0)
Warning message:
In stri_info(short = TRUE) :
  Your current locale is not in the list of available locales. Some functions may not work properly. Refer to stri_locale_list() for more details on known locale specifiers.

And ` stringi::stri_locale_set("zh_Hans_CN")`
>You are now working with stringi_1.0.1 (zh_Hans_CN.UTF-8; ICU4C 55.1 [bundle]; Unicode 7.0)

But didn't work. Thank you very much if you would  help me  solve this problem !

**Comment by krlmlr** [comment]
Thanks, we're working on improving UTF-8 support. Could you please post a stripped-down copy of your database? Which R client are you using (RGui, RStudio, ...)? Could you please also post the output of `devtools::session_info()`?

**Comment by BruceZhaoR** [comment]
Hello, Kirill Müller !  Thank you very much for answering my question!  I am a little busy recently,maybe next weekend I would post a simple table created by SQL.
Here are my R env :
> devtools::session_info()
Session info  ---------------------------------------------------------------
setting  value
version  R version 3.2.2 (2015-08-14) 
system   x86_64, mingw32 
 ui       RStudio (0.99.484) 
 language (EN)
 collate  Chinese (Simplified)_China.936
 tz       Asia/Taipei
 date     2015-11-08 
Packages  -----------------------------------------------------------------
 package  * version date       source 
 DBI      * 0.3.1   2014-09-24 CRAN (R 3.1.3)
 devtools   1.9.1   2015-09-11 CRAN (R 3.2.2)
 digest     0.6.8   2014-12-31 CRAN (R 3.1.2)
 memoise    0.2.1   2014-04-22 CRAN (R 3.1.2)
 RSQLite  * 1.0.0   2014-10-25 CRAN (R 3.2.2)

**Comment by BruceZhaoR** [comment]
###  I use the latest RSQLite and DBI,it seems worked.
![1](https://cloud.githubusercontent.com/assets/8092534/11056129/6663aa86-87b9-11e5-9f65-1efc885f3e60.png)
![2](https://cloud.githubusercontent.com/assets/8092534/11056132/6d558e90-87b9-11e5-8715-b40a707bce92.png)

### Thanks all the same.

**Comment by krlmlr** [comment]
Thanks for the heads up.
