### ISSUE TITLE
Ask SQLite to collect additional histogram data

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RSQLite#124]
for better query optimization by enabling `SQLITE_ENABLE_STAT4` during compile time.

https://www.sqlite.org/lang_analyze.html
https://www.sqlite.org/compile.html#enable_stat4

> The downside of this compile-time option is that it violates the query planner stability guarantee making it more difficult to ensure consistent performance in mass-produced applications.

Would that downside affects typical R users?

**Comment by hadley** [comment]
Seems reasonable to enable by default IMO.
