### ISSUE TITLE
reproducible example of two zero integer values not being distinct

### ISSUE THREAD

**Issue by ajdamico** [rstats-db/RSQLite#125]
library(downloader)

	setwd( "C:/My Directory/SBO/" )

	source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/39a82aa32155fd90ed00c3dae9302ab416e2a047/Survey%20of%20Business%20Owners/download%20and%20import.R" , prompt = FALSE , echo = TRUE )

	db <- dbConnect( SQLite() , sbo.dbname )

	# two zeroes!
	dbGetQuery( db , "SELECT healthins , COUNT(*) FROM y GROUP BY healthins" )
	  # healthins COUNT(*)
	# 1         0    70633
	# 2         1   512793
	# 3         2   957839
	# 4         0   624415

	# two zeroes!
	dbGetQuery( db , "SELECT distinct healthins FROM y" )
	  # healthins
	# 1         1
	# 2         2
	# 3         0
	# 4         0

	# pull the table creation line
	dbGetQuery( db , "SELECT sql FROM sqlite_master WHERE name = 'y'" )

	# look exactly at the `healthins` creation type..  it is an integer
	substr( dbGetQuery( db , "SELECT sql FROM sqlite_master WHERE name = 'y'" ) , 2650 , 2700 )
	# [1] "mpnr INT,\n  healthins INT,\n  retirement INT,\n  prof"

	# > sessionInfo()
	# R version 3.2.2 (2015-08-14)
	# Platform: i386-w64-mingw32/i386 (32-bit)
	# Running under: Windows 8 x64 (build 9200)

	# locale:
	# [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

	# attached base packages:
	# [1] grid      stats     graphics  grDevices utils     datasets  methods   base     

	# other attached packages:
	# [1] digest_0.6.8   survey_3.30-3  mitools_2.3    RSQLite_1.0.0  DBI_0.3.1      downloader_0.3

**Comment by hadley** [comment]
It seems likely that this a floating point SQL issue, not an RSQLite problem.

**Comment by ajdamico** [comment]
sent on to `sqlite-users@mailinglists.sqlite.org`  thanks hadley

**Comment by drhsqlite** [comment]
Probably some of your "0" values are numeric and others are text.  What do you get for this query:

SELECT DISTINCT typeof(healthins), healthins FROM y;

**Comment by ajdamico** [comment]
> dbGetQuery(db,"SELECT DISTINCT typeof(healthins), healthins FROM y")
	  typeof(healthins) healthins
	1           integer         1
	2           integer         2
	3              text         0
	4           integer         0
	>

**Comment by drhsqlite** [comment]
Easiest way to fix your data so that all healthins values are integers:  UPDATE y SET healtins=healtins+0;

**Comment by hannesmuehleisen** [comment]
@drhsqlite I am amazed it is possible to have values with multiple types within a SQL column... Somewhere, E. Codd must be turning in his grave.
