### ISSUE TITLE
Soft deprecate dbGetInfo()

### ISSUE THREAD

**Issue by hadley** [rstats-db/RSQLite#137]
I think a hard deprecation might be too challenging for this release.

**Comment by hadley** [comment]
Esp since dplyr uses it to access the version, and `rsqliteVersion` isn't exported in the released version.

**Comment by bborgesr** [comment]
Why are you deprecating this? (It's come in handy for the `pool` package)

**Comment by hadley** [comment]
@bborgesr because it's too generic - there's no specification about what it returns, so we've been moving toward individual methods.
