### ISSUE TITLE
dbListResults() on new RSQLite connection has length 1

### ISSUE THREAD

**Issue by nimame** [rstats-db/RSQLite#141]
When I create a new database like this:
```
> require(RSQLite)
> con <- dbConnect(dbDriver("SQLite"), dbname='sqlite.db'))
```
and then run `dbListResults`:
```
> dbListResults(con)
[[1]]
<SQLiteResult>
```
There seems to be an SQLiteResult. Running `fetch` or `dbClearResults` on that SQLiteResult gives an error:
```
> fetch(dbListResults(con)[[1]])
Error: Expired SQLiteResult
> dbClearResult(dbListResults(con)[[1]])
Error: Expired SQLiteResult
```
Is this a bug? This would break all my code that expects `length(dbListResults(con))==0` when there is no SQLiteResult, that has not been fetched.

My System:
- OS: Windows 10 64Bit
- R version 3.3.0
- RSQLite 1.0.0
- DBI 0.4-1 

Copied from: http://stackoverflow.com/questions/37574040/why-does-dblistresults-on-fresh-rsqlite-connection-issue-a-list-of-length-1-inst

**Comment by bborgesr** [comment]
Yes, @krlmlr, I can confirm this bug too. (I wonder if #143 is also related to this -- I got the same error when I tried to do a second `sendQuery` and there was already one open -- RSQLite should support several open result sets, no?)

Basically what is happening is that `dbListResults` returns always exactly one result set:

```r
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)

## There's no active results, so this should be an empty list
(rs <- dbListResults(con))
#> [[1]]
#> <SQLiteResult>

## Since the result above is not actually real, it's not valid
dbIsValid(rs[[1]])
#> [1] FALSE

## Create an actual result
res <- dbSendQuery(con, "SELECT * FROM mtcars WHERE cyl = 4;")

## Works as expected
(rs <- dbListResults(con))
#> [[1]]
#> <SQLiteResult>
dbIsValid(rs[[1]])
#> [1] TRUE

## Create a second result (without closing the first one) -- get
## back a warning and the first result is closed
res2 <- dbSendQuery(con, "SELECT * FROM mtcars WHERE cyl = 4;")
#> Warning message:
#> In sqliteSendQuery(conn, statement) : Closing result set with pending rows

## If this was working properly, this should have been two results...
(rs <- dbListResults(con))
#> [[1]]
#> <SQLiteResult>
dbIsValid(rs[[1]])
#> [1] TRUE

dbDisconnect(con)
```

Note: I came across this when implementing something for `pool` (see rstudio/pool#2)

**Comment by krlmlr** [comment]
I'd like to get rid of dbListResults() (https://github.com/rstats-db/DBI/issues/58).

**Comment by krlmlr** [comment]
Can't get rid of dbListResults() just yet.

**Comment by krlmlr** [comment]
Can't observe this anymore, but dbListResults() shouldn't be used anyway and raises a warning now.
