### ISSUE TITLE
Package vignette parameterized queries throws error

### ISSUE THREAD

**Issue by kissmygritts** [rstats-db/RSQLite#142]
The command below is taken directly from the vignette all previous commands had been run.

```
dbGetQuery(mydb, 'SELECT * FROM iris WHERE "Sepal.Length" < :x', params = list(x = 4.6))

Error in .local(conn, statement, ...) : 
  unused argument (params = list(x = 4.6))
```

This is may be related to DBI rather than RSQLite, however since this portion of your vignette isn't working I figure I'll bring it up here.

**Comment by mbertolacci** [comment]
Is this just broken in the current version is CRAN? Is there a way to parameterise SELECT statements at the moment? Everything I've tried throws the error above.

**Comment by krlmlr** [comment]
Thanks. Please see [?dbBind](http://rstats-db.github.io/DBI/dbBind.html) in the development version of DBI for the new syntax:

```r
devtools::install_github("rstats-db/DBI")
```

The next CRAN version of RSQLite will (again) support the `dbSendPreparedQuery()` and `dbGetPreparedQuery()` syntax, but perhaps deprecate it (#100).

**Comment by krlmlr** [comment]
The vignette looks good to me, it already contains the new `dbBind()` syntax.
