### ISSUE TITLE
Datetime values chopped in RSQLite depending on null values

### ISSUE THREAD

**Issue by meyera** [rstats-db/RSQLite#144]
I might have stumbled upon a bug in the RSQLite driver - see my entry at Stackoverflow: 

https://stackoverflow.com/questions/38256767/datetime-values-chopped-in-rsqlite-depending-on-null-values

**Comment by krlmlr** [comment]
Thanks for reporting this. I have answered your use case on SO, this will work better out of the box when the linked issue is fixed.
