### ISSUE TITLE
Loading table with NA values returns incorrect class

### ISSUE THREAD

**Issue by daynefiler** [rstats-db/RSQLite#145]
I received an email about the new version of `RSQLite` to be released on August 5 potentially breaking my package. I have downloaded the development version, and think I found a bug. Loading a table with `NA` values causes the class of the columns with `NA` values to be changed to 'character.' Please see the example below:

    library(RSQLite)
    library(data.table)
    
    ## Create a connection to a new database
    dbcon <- dbConnect(drv = SQLite(), db = "testdb.sqlite")
    
    ## Create a table, 'tb1'
    status <- dbSendQuery(dbcon, "CREATE TABLE tb1 (val DOUBLE);")
    status
    dbClearResult(status)
    
    ## Add a data.table with NA values to 'tb1'
    dat <- data.table(val = c(NA, 1:3, NA, 4:5))
    dbWriteTable(dbcon, "tb1", dat, append = TRUE)
    
    ## Load all of 'tb1'
    result <- DBI::dbGetQuery(dbcon, "SELECT * FROM tb1;")
    dbDisconnect(dbcon)
    
    ## 'val' has the wrong class 
    class(result$val)
    # [1] "character"

In the current version on CRAN the class returns as 'numeric.'

**Comment by krlmlr** [comment]
Thanks. I think this is the same as #74, but I'll keep this issue open to make sure I use the test case shown here.

**Comment by krlmlr** [comment]
@daynefiler: You need to use `REAL` instead of `DOUBLE` to properly declare the column affinity. Anyway, I'm working on making RSQLite work as expected also for your case.

**Comment by krlmlr** [comment]
@daynefiler: I'm mistaken, please disregard.

**Comment by krlmlr** [comment]
@daynefiler: Only partly. SQLite itself knows `DOUBLE` columns, but RSQLite currently doesn't. So, your code should work with `REAL` instead of `DOUBLE`, but `DOUBLE` will eventually work, too.

**Comment by krlmlr** [comment]
Column affinity will be handled in #160.
