### ISSUE TITLE
Rethink multiple open result sets

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RSQLite#150]
While it is now technically possible to have multiple open result sets in RSQLite, I fear that this will cause more problems than benefits in the long run. Furthermore, some database libraries may not allow more than one open result set anyway; I know this is true for old ADO, but it's conceivable that other libraries share this limitation.

I'd like to keep things as simple as possible here, and disallow multiple open result sets in the DBI specification. RSQLite 1.0.0 warns when opening a second result set, I'd like to revert to this behavior.

@hadley: What were the reasons why you allowed multiple open result sets in RSQLite?

**Comment by hadley** [comment]
@jcheng5 are multiple result sets common in other languages?

**Comment by krlmlr** [comment]
Will restrict RSQLite to one open result set for now, as in v1.0.0: lifting the restriction later is easy, the opposite will be quite hard.

**Comment by krlmlr** [comment]
Multiple *open* result sets should be forbidden, but it should be possible to reuse a cleared result set with another `dbBind()` call (for performance of prepared queries/statements).
