### ISSUE TITLE
dbWriteTable() to load CSV data

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RSQLite#151]
as in v1.0.0.

Tests in #149.

**Comment by cboettig** [comment]
@krlmlr Does this allow one to read in a (possibly compressed) tsv file without needing to load it into R first?  (a la https://cran.r-project.org/web/packages/sqldf/)  I'm not quite clear on how to invoke this.  Seems like it doesn't like compressed files? And the `sep` argument doesn't recognize `\\t` tabs?

```
dbWriteTable(con, "taxa", "data/taxa.tsv", delim = "\\t")
Error in connection_import_file(conn@ptr, name, value, sep, eol, skip)
```

**Comment by krlmlr** [comment]
The import code comes from SQLite3's shell, https://www.sqlite.org/cli.html, section 8. Compressed files are not supported, does `sep = "\t"` work?

The documentation at http://rsqlite.r-dbi.org/reference/dbwritetable leaves room for improvement. We could consider supporting compressed files.

**Comment by cboettig** [comment]
@krlmlr Thanks!

My solution to the issue of reading large, possibly compressed text files in and out of databases over a DBI connection without needing to uncompress the whole thing or to load the whole thing into memory was to write this little helper package, [arkdb](https://github.com/cboettig/arkdb).  Works nicely with RSQLite or anything else that supports a DBI connection (I've recently become a fan of MonetDB & MonetDBLite).  Probably not perfect but does work rather more generically than the miss-mash of different load/copy commands supported to such varying degrees by different databases.  Feedback on the package / approach welcome!  (It's in rOpenSci onboarding at the moment, hopefully off to CRAN after that).

**Comment by krlmlr** [comment]
Thanks for the pointer, this is a much more robust solution indeed. I wish data loading was supported in a more consistent way between databases, but there are differences regarding:

- SQL syntax
- CSV format
- location of the file (client file system vs. server file system)
