### ISSUE TITLE
dbWriteTable() not working when the raster package is loaded

### ISSUE THREAD

**Issue by ecodiv** [rstats-db/RSQLite#177]
Write a data.frame to an SQLite database using dbWriteTable() while the 'raster' package is loaded results in the warning "Error: C stack usage  7969204 is too close to the limit" .

When first running detach("package:raster", unload = TRUE) and restarting the R session (e.g., using .rs.restartR() in Rstudio), dbWriteTable() works without problem.

I am not sure if this is a problem of RSQLite, so if you think I should report this elsewhere, please let me know.

Ubuntu 16.04 64bits, R 3.3.1, RSQLite v 1.0.0

**Comment by krlmlr** [comment]
Thanks. Could you please provide a reproducible example?

**Comment by krlmlr** [comment]
I tried:

```r
library(raster)

library(DBI)
library(RSQLite)

con <- dbConnect(SQLite())
dbWriteTable(con, "iris", iris[rep(1:150, 10000),])
```

works for me, also when I load raster after RSQLite. Please provide a reproducible example.

**Comment by ecodiv** [comment]
Hi, sorry for the late response. The example you provide above does not work for me. Running:

```
library(raster)
library(DBI)
library(RSQLite)
con <- dbConnect(SQLite())
dbWriteTable(con, "iris", iris[rep(1:150, 10000),])
```
Gives me

`Error: C stack usage  7970772 is too close to the limit`

I am on Ubuntu 16.04, R 3.3.1, raster 2.5-8, RSQlite 1.0.0, DBI 0.5-1

**Comment by krlmlr** [comment]
Could you please try the development version?

**Comment by ecodiv** [comment]
Yes, with the development version, the code above gives me 'TRUE', so it seems to have solved the issue. Thanks!
