### ISSUE TITLE
time to update SQLite?

### ISSUE THREAD

**Issue by phaverty** [rstats-db/RSQLite#180]
From the version number in the SQLite header file, it looks like the SQLite version bundled with RSQLite is not so current. SQLite recently had a new release, so this is a good time to upgrade.

**Comment by krlmlr** [comment]
Yeah, I'm going to update right after CRAN release, which will happen pretty soon, so that we have time to test it.

**Comment by rtanalytics** [comment]
Hi,
Do you have any update on this?
