### ISSUE TITLE
bulk insert

### ISSUE THREAD

**Issue by GiovanninoPaneEvino** [rstats-db/RSQLite#184]
Hello,
may I ask suggestion on the best way to make big insert (~100K rows per insert) from data.frames? 

Thank you very much!!!!!!!

**Comment by krlmlr** [comment]
Use transactions and a prepared query, ideally in the development version which is about to hit CRAN:

```r
con <- dbConnect(...)
rs <- dbSendStatement("INSERT INTO xxx VALUES(:f1, :f2, :f3, ...)")
dbBind(rs, data.frame(f1 = 1:100000, f2 = rev(1:100000), f3 = sample.int(100000))
dbClearResult(rs)
dbDisconnect(con)
```
