### ISSUE TITLE
dbSendPreparedQuery

### ISSUE THREAD

**Issue by dmenne** [rstats-db/RSQLite#191]
I believe the soft-deprecated (#153) dbSendPreparedQuery creates a confusing error message. "Named parameters not used in query".  It still works, but I do not understand what to use as the alternative params syntax with dbExecute. Note that I use it for Autoincrement with bulk inserts, which works ok when the field is NA in the data frame

```
# Parametrized queries
library(DBI)
library(RSQLite)

# Adapt dbname here
con <- dbConnect(RSQLite::SQLite(), dbname = "C:/tmp/testparquery.sqlite")

if (!dbExistsTable(con, "PatientAuto")) {
  createAuto =
    'CREATE TABLE IF NOT EXISTS PatientAuto (
    PatientID INTEGER  PRIMARY KEY AUTOINCREMENT  NOT NULL ,
    Name TEXT
  )'

  createId =
    'CREATE TABLE IF NOT EXISTS Patient (
    PatientID INTEGER PRIMARY KEY NOT NULL ,
    Name TEXT
  )'


  dbExecute(con, createAuto)
  dbExecute(con, createId)
} else {
  dbExecute(con, "DELETE from PatientAuto")
  dbExecute(con, "DELETE from Patient")
}

params = data.frame(PatientID = c(1,2), Name = c("Einstein", "Freud"))
paramsAuto = data.frame(PatientID = c(NA,NA), Name = c("Einstein", "Freud"))

# Warns about unused parameters, but works
# "Named parameters not used in query: PatientID, Name"
# This is "soft-deprecated
# https://github.com/rstats-db/RSQLite/issues/153
ret = dbSendPreparedQuery(con, "INSERT INTO  Patient VALUES(?,?)", bind.data = params)
dbClearResult(ret)
dbGetQuery(con, "SELECT * from Patient")

# Using NA for Autoincrement parameters
# Warns about unused parameters, but works
ret = dbSendPreparedQuery(con, "INSERT INTO  PatientAuto VALUES(?,?)", bind.data = paramsAuto)
dbClearResult(ret)
dbGetQuery(con, "SELECT * from PatientAuto")

# Cleanup
dbExecute(con, "DELETE from PatientAuto")
dbExecute(con, "DELETE from Patient")

# What is the suggested alternative? The versions below do not work
dbExecute(con,  "INSERT INTO  Patient VALUES(?,?)", params = params )
dbExecute(con,  "INSERT INTO  Patient VALUES(?,?)", params = list(PatientID = 1, Name = "Hallo") )

### Added after Kiril's suggestion (works!)
dbExecute(con, "INSERT INTO PatientAuto VALUES($PatientID,$Name)", params = paramsAuto )

dbDisconnect(con)

```

**Comment by krlmlr** [comment]
Have you tried:

```r
dbExecute(con,  "INSERT INTO  Patient VALUES(?,?)", params = list(1, "Hallo") )
dbExecute(con,  "INSERT INTO  Patient VALUES($PatientID,$Name)", params = list(PatientID = 1, Name = "Hallo") )
```

Happy to take suggestions for improving error reporting.

**Comment by dmenne** [comment]
Thanks, that works, but I could not find in the docs that "?" params must not be names, and $Name can be? I  might have missed it, I only found a comment in DBI that it is "driver-specific".

But it's only part of the story: note that the dbSendPreparedQuery works for data frames, allowing for bulk updates. That's helpful when you have Autoincrement, because I could not get writeTable to work with it.

Suggestion for error reporting: dbSendQuery in my example produces a warning. If it's really not justified, maybe don't issue it? Or did I miss some subtle issues?

**Comment by krlmlr** [comment]
I'll make sure to make this more prominent in the [documentation](http://rstats-db.github.io/RSQLite/reference/sqlite-query.html) -- currently the only hint is in the examples, and the param documentation incorrectly states that it must be a named list.

dbExecute() also should work for data frames, or lists of vectors of the same length.

Named SQL parameters require a named list, unnamed SQL parameters require an unnamed list. I could certainly ignore the names if all SQL parameters are unnamed.

**Comment by dmenne** [comment]
>>dbExecute() also should work for data frames, or lists of vectors of the same length.

I had tried: 
`dbExecute(con,  "INSERT INTO  PatientAuto VALUES(?, ?)", params = paramsAuto )`

which failed, but this works:
`dbExecute(con,  "INSERT INTO  PatientAuto VALUES($PatientID,$Name)", params = paramsAuto )
`

Thanks a lot for the fast answer - there are real patients who are waiting for the update of dmenne/d13cbreath. And feel free to add the above example to the docs, there are not many sources online about parametrize queries with R and Sqlite.

**Comment by krlmlr** [comment]
The following should work:

```r
dbExecute(con, "INSERT INTO PatientAuto VALUES(?, ?)", params = unname(as.list(paramsAuto)) )
```

**Comment by dmenne** [comment]
Suggested error message:
"Named parameters not used in query: PatientID, Name"; use $PatientID, $Name instead of '?' with named lists.
