### ISSUE TITLE
SQLITE_MAX_COLUMN too low

### ISSUE THREAD

**Issue by dagtann** [rstats-db/RSQLite#195]
How can I change the SQLITE_MAX_COLUMN parameter after updating to RSQLite 1.1? I am working with several large databases (e.g. [Quality of Government standard  data](http://qog.pol.gu.se/data/datadownloads)) which include more than 2000 columns.

**Comment by krlmlr** [comment]
Thanks. Unfortunately, this is a compile-time limit, f80b407c is the relevant change.

The limit was at 30000 before. What's a reasonable limit? According to the NEWS, it has been reduced because setting it too large can hurt performance.

I can release a hotfix to CRAN.

**Comment by dagtann** [comment]
Thank you, Kirill. Probably, any reasonable limit depends on your project. 

For years the team behind the QoG dataset has categorised their data thematically. Hence, you might argue that poor optimisation causes all the trouble. 

Anyhow, I won't require a hotfix. For the time being I downgraded to 1.0, and I'll "cut the data to pieces" in the next couple of days.

**Comment by krlmlr** [comment]
Thanks. The limit seems to be at 2000 by default. Closing for now.
