### ISSUE TITLE
problem with RSQLite 1.1-1 and sqldf

### ISSUE THREAD

**Issue by ggrothendieck** [rstats-db/RSQLite#196]
On this page it was reported that there is a problem using sqldf with RSQLite after upgrading to RSQLite 1.1-1.   

  http://stackoverflow.com/questions/41511901/sqldf-create-table-from-data-frame-error-no-such-table-and-two-tables-crea 

I haven't looked into it but it was confirmed by the user that downgrading back to RSQLite 1.0.0 resolves the problem.  Please fix.

**Comment by krlmlr** [comment]
I do wonder why sqldf passes R CMD check with the RSQLite rewrite but fails with a seemingly basic usage scenario.

Please consider fixing sqldf to remove the warnings given by RSQLite. The table identifiers passed to `dbWriteTable()` are not supposed to be quoted.

**Comment by ggrothendieck** [comment]
Note that I already updated sqldf to address incompabilities introduced in RSQLite 1.0.0 so this would be two RSQLite versions in a row to introduce incompatibilities with existing software.

**Comment by krlmlr** [comment]
Thanks. Did that update reach CRAN yet?

**Comment by aminadibi** [comment]
Seems to be problematic again in v2, unless sqldf v0.4-11 is used. Perhaps make it a requirement?

**Comment by krlmlr** [comment]
I've thought about adding sqldf to "Enhances" with a versioned dependency, but I'm not sure R will enforce this. sqldf v0.4-11 is on CRAN now and built for almost all platforms, users that update RSQLite will usually also get the update for sqldf.
