### ISSUE TITLE
Connecting to a locked database, message that looks like an error

### ISSUE THREAD

**Issue by gaborcsardi** [rstats-db/RSQLite#197]
Prints this: 
```
Error in rsqlite_send_query(conn@ptr, statement) : database is locked
```
which is very misleading, because it does create the valid connection, and this is not really an error, just a message. I am not sure where it is coming from, maybe from the C client and then it is hard to fix. To reproduce, just create a DB from one process (or the shell), and lock it, then connect from another process:

```
❯ sqlite3 /tmp/xxx
SQLite version 3.8.5 2014-08-15 22:37:57
Enter ".help" for usage hints.
sqlite> BEGIN EXCLUSIVE;
```

```r
library(DBI)
con <- dbConnect(RSQLite::SQLite(), "/tmp/xxx")
#> Error in rsqlite_send_query(conn@ptr, statement) : database is locked
con
#> <SQLiteConnection>
#>  Path: /private/tmp/xxx
#>  Extensions: TRUE
```

**Comment by krlmlr** [comment]
It's the `try()` calls in `dbConnect()`, a message that setting `PRAGMA synchronous` has failed should be printed instead. You can turn off the misleading message by asking `dbConnect(synchronous = NULL)` .

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by gaborcsardi** [comment]
Btw. does this have any consequences, I mean, if setting the PRAGMA fails?

**Comment by krlmlr** [comment]
Writing is [a tad slower](https://www.sqlite.org/pragma.html#pragma_synchronous). I wonder why setting the PRAGMA fails when the DB is locked; it's not documented whether the PRAGMA setting is persistent or connection-local.

**Comment by gaborcsardi** [comment]
I know some pragmas belong to the connection, e.g. the busy timeout.

But it seems that this one belongs to the database.

**Comment by krlmlr** [comment]
That would mean that setting it for every connection is plain wrong.

**Comment by gaborcsardi** [comment]
Yeah, I take it back. It does belong to the connection.

**Comment by gaborcsardi** [comment]
I don't have a reference, just saw that it reverts back to the default if you close the connection that set it.

**Comment by gaborcsardi** [comment]
Anyway, it seems that `RSQLite` cannot really do much about this, except maybe give a better message.

**Comment by gaborcsardi** [comment]
:+1:

**Comment by krlmlr** [comment]
I'm not sure if thread safety is an issue -- R is single-threaded. Either way, can you please open a new issue?
