### ISSUE TITLE
Suggestion for daisy-chained methods 

### ISSUE THREAD

**Issue by stefanedwards** [rstats-db/RSQLite#205]
I am using RSQLite with dplyr chains. An example could be part of a computation pipeline, where output from a program is summarised and saved in a SQLite database:

    read.table('results.txt', col.names=c('group','estimate')) %>%
      group_by(group) %>% summarise(m=mean(estimate)) %>%
     dbSendQuery(conn=connection, statement='INSERT INTO results (group, mean) VALUES (:group, :m);')

Being the lazy programmer I am, I would like to avoid having to explicitly state the argument names. Or, use the daisy-chain result for the 3rd argument, not the first.

**Suggestion:**

Add methods for `dbSendQuery` and `dbGetQuery` that accepts `data.frame` and/or other tibbles as first argument. Using `setMethod` with a data.frame signature seems to work for me:

```
setMethod("dbSendQuery",
          signature(conn = "data.frame"),
          function (params, conn, statement, ...) 
          {
            dbSendQuery(conn, statement, params, ...)
          }
)
setMethod("dbSendQuery",
          signature(conn = "list"),
          function (params, conn, statement, ...) 
          {
            dbSendQuery(conn, statement, params, ...)
          }
)
setMethod("dbGetQuery",
          signature(conn = "data.frame"),
          function (params, conn, statement, ...) 
          {
            dbGetQuery(conn, statement, params, ...)
          }
)
setMethod("dbGetQuery",
          signature(conn = "list"),
          function (params, conn, statement, ...) 
          {
            dbGetQuery(conn, statement, params, ...)
          }
)
```

The result of these is to allow the above example to be written simpler as:
```
read.table('results.txt', col.names=c('group','estimate')) %>%
  group_by(group) %>% summarise(m=mean(estimate)) %>%
  dbSendQuery(connection, 'INSERT INTO results (group, mean) VALUES (:group, :m);')
```

The only remaining issue, for me, is that with one of the newer releases of DBI or RSQLite, the `params` argument must not contain unused bindings which must be manually removed beforehand by e.g. `select`.

**Comment by krlmlr** [comment]
You can also write:

```r
... %>% dbSendQuery(connection, 'INSERT INTO results (group, mean) VALUES (:group, :m);', .)
```

This issue belongs in DBI, but it's unlikely that we'll be supporting forwarders with permuted arguments there.
