### ISSUE TITLE
dbConnect failed when path with umlaut (ü,ö,ä)

### ISSUE THREAD

**Issue by jackrabbit7** [rstats-db/RSQLite#211]
Since update to R version 3.3.2 i can't connect to SQLite database when in path (setwd()) characters like ö or ä.

**Comment by krlmlr** [comment]
Thanks for reporting. What OS are you on? Could you please show a reproducible example?

**Comment by jackrabbit7** [comment]
Thanks for your answer.
The reason is maybe not the new version of R, a co-worker of me has the
same problem now with version 3.2.2. In the past it works fine everytime.

Windows 7 Professional
Service Pack 1
i5-3570 CPU @ 3,4 GHz
64 Bit

#######################################
library(DBI)

path <- "Z:/AG/Qualit*ät_Ä*stuare/Intern/Datenbanken"

setwd(path)

file <- "Estuary.sqlite"

con <- DBI::dbConnect(RSQLite::SQLite(), file, create = FALSE)

########################################
# here comes the error:
#Error in rsqlite_connect(dbname, loadable.extensions, flags, vfs) :
#  Could not connect to database:
#unable to open database file

> traceback()
9: stop(list(message = "Could not connect to database:\nunable to open
database file",
       call = rsqlite_connect(dbname, loadable.extensions, flags,
           vfs), cppstack = list(file = "", line = -1L, stack = "C++ stack
not available on this system")))
8: .Call("RSQLite_rsqlite_connect", PACKAGE = "RSQLite", path, allow_ext,
       flags, vfs)
7: rsqlite_connect(dbname, loadable.extensions, flags, vfs)
6: initialize(value, ...)
5: initialize(value, ...)
4: new("SQLiteConnection", ptr = rsqlite_connect(dbname,
loadable.extensions,
       flags, vfs), dbname = dbname, flags = flags, vfs = vfs,
loadable.extensions = loadable.extensions,
       ref = new.env(parent = emptyenv()))
3: .local(drv, ...)
2: DBI::dbConnect(RSQLite::SQLite(), file, create = FALSE)
1: DBI::dbConnect(RSQLite::SQLite(), file, create = FALSE)

########################################
Best regards
Holger



2017-04-24 0:04 GMT+02:00 Kirill Müller <notifications@github.com>:

**Comment by krlmlr** [comment]
Thanks. Could you please paste the log directly to GitHub, or to a gist? The e-mail already seems to have distorted it.

**Comment by jackrabbit7** [comment]
addition:
when i use RJDBC it works furthermore

drv <- JDBC("org.sqlite.JDBC", "D:/OWN/Workbench/sqlite-jdbc-3.15.1.jar")
con <- dbConnect(drv, "jdbc:sqlite:Z:/AG/Qualität_Ästuare/Intern/Datenbanken/Estuary.sqlite")

**Comment by krlmlr** [comment]
Thanks, could you please try the development version?

**Comment by jackrabbit7** [comment]
Thanks a lot! It works fine again...

**Comment by jackrabbit7** [comment]
Okay, the connection works. But there is a new problem.
My procedure is to query some tables to get dataframes of it and then to work with sqldf().
Now i get the error:
Error in rsqlite_send_query(conn@ptr, statement) : no such table: tableX1
I have deinstalled your development version, reinstalled RSQLite from CRAN, connected the database with RJDBC and sqldf() works again.

**Comment by krlmlr** [comment]
Could you please try the dev version of RSQLite + the [dev version of sqldf](https://github.com/ggrothendieck/sqldf)? Please open a new issue if problems persist.
