### ISSUE TITLE
Export function dbExecute

### ISSUE THREAD

**Issue by stefanedwards** [rstats-db/RSQLite#212]
Shouldn't the new `dbExecute` be an exported function? 

I have DBI_0.5-1 and RSQLite_1.1-2 and can only access `dbExecute` by specifying `DBI::dbExecute`.

**Comment by krlmlr** [comment]
Fixed in 1.1-14, but please note you need to `import(RSQLite, dbExecute)` or `importMethodsFrom(DBI, dbExecute)` in a package's `NAMESPACE` file.
