### ISSUE TITLE
dplyr::union_all errors out if data is "headed"

### ISSUE THREAD

**Issue by JohnMount** [rstats-db/RSQLite#215]
dplyr::union_all errors out if data is "headed", adding the commented out compute step back in fixes the issue.  Also filed as [dplyr 2858](https://github.com/tidyverse/dplyr/issues/2858).

``` r
suppressPackageStartupMessages(library('dplyr'))
packageVersion('dplyr')
#> [1] '0.7.0'
packageVersion('dbplyr')
#> [1] '1.0.0'
my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
dr <- dplyr::copy_to(my_db,
                     data.frame(x=c(1,2),y=c('a','b'),
                                stringsAsFactors = FALSE),
                     'dr',
                     overwrite=TRUE)
dr <- head(dr,1)
# dr <- compute(dr)
print(dr)
#> # Source:   lazy query [?? x 2]
#> # Database: sqlite 3.11.1 [:memory:]
#>       x     y
#>   <dbl> <chr>
#> 1     1     a
print(dplyr::union_all(dr,dr))
#> Error: SQLite does not support set operations on LIMITs
```

**Comment by krlmlr** [comment]
Thanks, this belongs in dplyr. Please avoid posting issues here that need dbplyr in their reprex, because RSQLite really implements only the interface to the database, and not the generation of SQL queries.

**Comment by JohnMount** [comment]
The related issue was closed in <code>dplyr</code> 7 days ago with the comment "There's nothing we can do here - SQLite doesn't support this SQL."
