### ISSUE TITLE
Table not found

### ISSUE THREAD

**Issue by jacob-bedard-o2e** [rstats-db/RSQLite#221]
The new RSQLite seems to break sqldf, apparently. It says it can't find my tables. I looked this up and the sqldf package team has traced this issue back to the new RSQLite version.

**Comment by krlmlr** [comment]
Duplicate of #216 and #219. Please use the GitHub version of sqldf until the update has been pushed to CRAN.

**Comment by krlmlr** [comment]
Related: https://github.com/ggrothendieck/sqldf/issues/15
