### ISSUE TITLE
Why backticks in `name` 

### ISSUE THREAD

**Issue by dmenne** [rstats-db/RSQLite#234]
On recompiling old code, I got the message:

    Please use  `name` = "<savepoint>" to specify the name of the savepoint.

I there special meaning in the backticks?  Why not simply 

`name = "<savepoint>"`

**Comment by krlmlr** [comment]
They're redundant, but indicate an identifier, and make it clear that what follows is code and not text. Maybe the following is better?

```
Please use dbBegin(name = "<savepoint>") to specify the name of the savepoint.
```

**Comment by dmenne** [comment]
Yep! I just stumbled over it because there was another error, and then I tried backticks and variants.
