### ISSUE TITLE
substring_index

### ISSUE THREAD

**Issue by ggrothendieck** [rstats-db/RSQLite#47]
Would be nice to have the MySQL `substring_index` function in `extension-functions.c`.  Since parsing fields consisting of delimited subfields, e.g.  `AB,D,EFG,H` can be fairly difficult with only the supplied functions.  See: http://dev.mysql.com/doc/refman/5.0/en/string-functions.html#function_substring-index

**Comment by hadley** [comment]
I'd be happy to review a pull request, but I don't have a need for this myself at the moment.
