### ISSUE TITLE
Doesn't work in parallel

### ISSUE THREAD

**Issue by ivannp** [rstats-db/RSQLite#56]
Below is a small program which simply uses two R process's to insert integers into a table. The table is created as "create table vals (value integer not null)". I created it outside the driver function simply to investigate whether it's an issue between the main the child process. It's not. After about 50 inserts, I get an error, which is not helpful since R loses the actual error when mcapply is used.

In any case, I tried starting and ending a transaction, as well as unloading the driver - same. Looks like the database gets locked and the other writes fail.

```
require(RSQLite)
require(parallel)

write.one.value = function(val, db.path)
{
   driver = SQLite()
   connection = dbConnect(driver, dbname=db.path)

   data = expand.grid(val)
   colnames(data) = c("value")
   query = paste("insert into vals (value) values (@value)", sep="")
   dbGetPreparedQuery(connection, query, bind.data=data)
   dbDisconnect(connection)
}

write.values = function(db.path)
{
   res = mclapply(seq(1,100,1), write.one.value, mc.cores=2, db.path=db.path)
}

# write.values("~/db.sqlite")
```

**Comment by dernst** [comment]
SQLite's default behaviour is that it tests whether another process already has a file lock and if so it returns SQLITE_BUSY. This behaviour can be altered by setting a busy handler, for example with "PRAGMA busy_timeout". The timeout might still be reached but you can just retry the write operation if SQLITE_BUSY was returned (sort of like EAGAIN for non-blocking sockets).

This code works for me (tm) on Linux:
```r
require(DBI)
require(parallel)

dbpath <- tempfile()
con <- dbConnect(RSQLite::SQLite(), dbname = dbpath)
df <- data.frame(value = 0)
dbWriteTable(con, "test", df)

write.one.value <- function(val) {
  con <- dbConnect(RSQLite::SQLite(), dbname = dbpath)
  res <- dbSendQuery(con, "PRAGMA busy_timeout=5000;")
  dbClearResult(res)

  on.exit(dbDisconnect(con))

  repeat {
    rv <- try(dbWriteTable(con, "test", data.frame(value = val), append = TRUE))
    if(!is(rv, "try-error")) break
  }
  rv
}

dbClearResult(dbSendQuery(con, "DELETE FROM test"))

ret <- mclapply(1:30, write.one.value, mc.cores = 4)
x <- dbReadTable(con, "test")
sum(x$value) == sum(1:30)  # should be TRUE
```

But that depends on whether file locks work properly. As the SQLite manual states some NFS implementations have problems with that (http://www.sqlite.org/lockingv3.html). As said it works for me on Linux but for example some writes don't go through on FreeBSD even though dbWriteTable returns TRUE. But not sure yet if it's a RSQLite, SQLite or FreeBSD issue. 
IMO OP's problem is not a RSQLite issue but rather depends on how SQLite is implemented. The more elegant solution would probably to explicitly use locks in write.one.value with e.g. synchronicity.

**Comment by wlandau** [comment]
FYI: I just ran into this problem in https://github.com/r-lib/liteq/issues/17. For what it's worth, [`liteq`](https://github.com/r-lib/liteq) uses the [same file locking mechanism](https://github.com/r-lib/liteq/blob/23ca7f8cd69f1816a88de5602a3ae358c913ecb8/R/db.R#L72) as in https://github.com/r-dbi/RSQLite/issues/56#issuecomment-70710256.
