### ISSUE TITLE
Error: unable to find an inherited method for function ‘dbConnect’ for signature ‘"character"’

### ISSUE THREAD

**Issue by psychemedia** [rstats-db/RSQLite#57]
Updating to the latest version of RSQLite today on Mac/Mavericks I get:

```
dbConnect(drv='SQLite', dbname='./testdb.sqlite')
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbConnect’ for signature ‘"character"’
```

**Comment by johnbaums** [comment]
Note that `RSQLite::SQlite()` should read `RSQLite::SQLite()`

**Comment by DSLituiev** [comment]
I had the same issue. Now running `dbConnect(RSQLite::SQlite(), dbname="my.db")` returns:

```error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error: 'SQlite' is not an exported object from 'namespace:RSQLite'```

[1] DBI_0.4          RSQLite_1.0.9002

**Comment by DSLituiev** [comment]
It looks like there is a typo in @hadley's post: it must be spelled with capital "L":
```
library(DBI)
dbConnect(RSQLite::SQLite(), ...)
```
