### ISSUE TITLE
rApache and RSQLite (3.8) on CentOS6

### ISSUE THREAD

**Issue by mbacou** [rstats-db/RSQLite#60]
I have a problem using RSQLite 1.0.0 with rApache. In an interactive R console, everything works as expected, but when sending a request to the same package with OpenCPU/rApache, I get a version mismatch error.

```sh
$ curl http://198.105.216.164/ocpu/library/hcapi3/R/getLayer/json -d '{"var" : ["whea_h", "AEZ16_CLAS"], "by" : "ADM1_NAME_ALT"}' -X POST -H "Content-Type:application/json"
error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error in SQLite(shared.cache = T) :
  SQLite mismatch between compiled version 3.8.6 and runtime version 3.6.20
```

SQLite 3.8 doesn't seem available from CentOS6 repos, so not sure what's the easiest way around.

Thanks, --Mel.

**Comment by hadley** [comment]
This should be resolved in the dev version since we now always use the bundled sqlite
