### ISSUE TITLE
Bug when using R*tree module

### ISSUE THREAD

**Issue by thomasp85** [rstats-db/RSQLite#61]
I have an open question on StackOverflow (http://stackoverflow.com/questions/26816880/debugging-sqlite-rtree), where a commenter indicated that my problem was related to an RSQLite bug. The SO question comes with a minimal example, but in essence:

When creating an R*tree the comparator querying gets broken. Asking for all records where a value is above a certain level would yield no results, even though there is lots of records with higher values (again it is all described more thoroughly in the SO question).

Is it possible to examine whether it is indeed a bug in RSQLite that causes this behaviour?

**Comment by hadley** [comment]
No idea, sorry.
