### ISSUE TITLE
Has a dependency on R version >= 3.0

### ISSUE THREAD

**Issue by Derek-Jones** [rstats-db/RSQLite#67]
The file "connection.R" has a call to setClass that sets the named parameter 'slots'.  This parameter is not in R prior to version 3 (at least the ones I am using).

This dependency needs to be flagged, otherwise a fail to dynamically load message appears at install time (which might confuse some folk).

**Comment by hadley** [comment]
Now flagged in the DESCRIPTION. Thanks for reporting!
