### ISSUE TITLE
Problem with dbSendQuery() and an update query  

### ISSUE THREAD

**Issue by tisseuil** [rstats-db/RSQLite#68]
Hi, 

When applying the dbSendQuery() function to modify values from a primary key of a parent table, the related value in the child table is not updated in cascade. Any explanations ? 

Thanks in advance

Clement

library(RSQLite)
db <- datasetsDb()
dbListTables(db)

## Create tables
dbSendQuery(db, "CREATE TABLE artist(
  artistid    INTEGER PRIMARY KEY, 
  artistname  TEXT
);")

dbSendQuery(db, "CREATE TABLE track(
  trackid     INTEGER,
  trackname   TEXT, 
  trackartist INTEGER REFERENCES artist(artistid) ON UPDATE CASCADE
);")

## Fill values in the tables
dbSendQuery(db, "INSERT INTO artist VALUES(1, 'tutu')")
dbSendQuery(db, "INSERT INTO artist VALUES(2, 'toto')")
dbSendQuery(db, "INSERT INTO artist VALUES(3, 'lulu')")
dbGetQuery(db, "select * from artist")

dbSendQuery(db, "INSERT INTO track VALUES(1, 'track1', 1)")
dbSendQuery(db, "INSERT INTO track VALUES(2, 'track2', 1)")
dbSendQuery(db, "INSERT INTO track VALUES(3, 'track3', 1)")
dbSendQuery(db, "INSERT INTO track VALUES(4, 'track1', 2)")
dbGetQuery(db, "select * from track")

## Update id value in the parent table
dbSendQuery(db, "UPDATE artist SET artistid = 4 WHERE artistid = 1")
dbGetQuery(db, "select * from artist")

## Update in the child table is not taken into account
dbGetQuery(db, "select * from track")

dbDisconnect(db)

**Comment by hadley** [comment]
This sounds like an SQLite question, not a RSQLite question.

**Comment by tisseuil** [comment]
Hi, 

Well, the update is working fine when using SQLite via the shell... 

Did you run the example to confirm that it does not come from a RSQLite error ? 

I am using RSQLite V1.0.0, and SQLite V3.7.9. 

Thanks for your understanding. 

Clement

**Comment by hadley** [comment]
I can't see how it could be an RSQLite problem because all it does is send the SQL to SQLite

**Comment by tisseuil** [comment]
Yes I totally agree! In theory !

However, in practice, the problem is that the error i.e. the infringement
of database constraints only happens when passing SQLite queries via
RSQLite. I just do not understand ...

Have you tried to reproduce the error ?

Thanks

Cheers

Clem



2015-02-08 21:29 GMT+01:00 Hadley Wickham <notifications@github.com>:

> I can't see how it could be an RSQLite problem because all it does is send
> the SQL to SQLite
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/rstats-db/RSQLite/issues/68#issuecomment-73429841>.
>



-- 
Clément Tisseuil
