### ISSUE TITLE
Shared in-memory databases

### ISSUE THREAD

**Issue by jazzycamel** [rstats-db/RSQLite#70]
Opening a database in-memory with a URI path results in a file being created on disk rather than a named, shared database being created in memory as detailed here: https://www.sqlite.org/inmemorydb.html

For example, the following should create an in-memory database named memdb1 with a shared cache:

> library(DBI)
> con<-dbConnect(RSQLite::SQLite(), "file:memdb1?mode=memory&cache=shared")

Is this possible via a different syntax, option or command or can I request this as a new feature?

**Comment by hadley** [comment]
It looks like the problem is the use of `path.expand(dbname)` in `dbConnect`. This is needed so paths like `~/abc.sqlite3` work, but has the unfortunate side effect of mangling special paths.

**Comment by jazzycamel** [comment]
Could we add a keyword argument (`URI=TRUE|FALSE`) to dbConnect which would circumvent the `path.expand(dbname)` if set? If this defaulted to `FALSE` then we could preserve backward compatibility whilst supporting URI based connections.

**Comment by hadley** [comment]
Or just test for `file:` at the start of the name?

**Comment by jazzycamel** [comment]
Works for me.
