### ISSUE TITLE
Strategy for type inference and manual coercion

### ISSUE THREAD

**Issue by hadley** [rstats-db/RSQLite#74]
`dbFetch()` and `dbGetQuery()` need to have optional coercion object. Should be named list, and provide common converters (e.g. times to number of seconds, dates to days, factors to strings, binary serialisation (default for list, raw should stay as is) etc, bool<->int for sqllite). 

Defaults only need to work with atomic vectors.

**Comment by marciz** [comment]
This might be related and to #38 . I  would expect last two columns to be character. 

```
library(RSQLite)

df <- data.frame(
  dt11=as.character(c('2011-01-01','2011-03-03','2011-12-31')),
  dt12=as.character(c('2011-01-01',NA,'2011-12-31')),
  dt13=as.character(c(NA,'2011-03-03','2011-12-31')),
  
  dt11=as.character(c('2011-01-01','2011-03-03','2011-12-31')),
  dt12=as.character(c('2011-01-01',NA,'2011-12-31')),
  dt13=as.character(c(NA,'2011-03-03','2011-12-31')),
  
  dt31=as.character(c('2011-01-01','2011-03-03','2011-12-31')),
  dt32=as.character(c('2011-01-01',NA,'2011-12-31')),
  dt33=as.character(c(NA,'2011-03-03','2011-12-31')),
  dt34=as.character(c(NA,'abc','xyz'))
)

df

sqlite <- dbDriver("SQLite")
tmpdb  <- dbConnect(sqlite,":memory:")      

dbGetQuery(tmpdb, "create table t (dt11 text, dt12 text, dt13 text, dt21, dt22, dt23, dt31 foo, dt32 foo, dt33 foo, dt34 foo)")
dbGetPreparedQuery(tmpdb, "insert into t values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", df) 
a <- dbGetQuery(tmpdb,'select * from t')

str(a)

dbDisconnect(tmpdb)   
```

>'data.frame':	3 obs. of  10 variables:
> $ dt11: chr  "2011-01-01" "2011-03-03" "2011-12-31"
> $ dt12: chr  "2011-01-01" NA "2011-12-31"
> $ dt13: chr  NA "2011-03-03" "2011-12-31"
> $ dt21: chr  "2011-01-01" "2011-03-03" "2011-12-31"
> $ dt22: chr  "2011-01-01" NA "2011-12-31"
> $ dt23: chr  NA "2011-03-03" "2011-12-31"
> $ dt31: chr  "2011-01-01" "2011-03-03" "2011-12-31"
> $ dt32: chr  "2011-01-01" NA "2011-12-31"
> $ dt33: num  NA 2011 2011
> $ dt34: num  NA 0 0


Thanks

**Comment by krlmlr** [comment]
I think type inference should work "properly" out of the box, to minimize surprise, at least for the built-in data types. The behavior should mimic type.convert().

**Comment by krlmlr** [comment]
This looks really difficult to get right, especially because BLOBs are lists, and everything else is a vector. Suggesting the following rules:

- The first non-NULL value decides the type of the column.
- If all values are NULL, the result is a logical vector of NAs.
- The declared data type of a column wouldn't be taken into account.

**Comment by krlmlr** [comment]
Better:

- Each dbFetch() call is allowed to return different column types
- Declared column type is used on start
- Types get coerced to fit all data values (int -> character, time -> character)

**Comment by krlmlr** [comment]
Need to add test cases when column affinity != column contents, e.g.:

```r
library(tibble)
library(DBI)

a <- tibble(a = c(NA_integer_), b = 1)
b <- tibble(a = c("2014-06-04 00:00:00"), b = 2)

con <- dbConnect(RSQLite::SQLite(), ":memory:")

dbWriteTable(con, "test", a)
dbWriteTable(con, "test", b, append = TRUE)

dbReadTable(con, "test")
```

**Comment by krlmlr** [comment]
Type inference for corner cases (zero-length data frames, NA values) is crucial for revdeps.

**Comment by krlmlr** [comment]
It seems to occur fairly often that the column type is declared as character. We can't rely on the affinity as start value.

Therefore:

- Each dbFetch() call is allowed to return different column types
- An unspecified column type is used on start
- Columns get coerced to fit all data values (int -> character, time -> character)
- Only if all columns were NULL, the column affinity is used

**Comment by krlmlr** [comment]
If affinity is character, all values are, too.

To clean up:

- Affinity is discussed in #160 
- NULL values in first row are #111 (basically resolved), currently implemented heuristics: https://github.com/rstats-db/RSQLite/issues/74#issuecomment-196423751 (without the warnings, #161)
- Manual column conversion should be perhaps specified in DBI (https://github.com/rstats-db/DBI/issues/137)
