### ISSUE TITLE
Parameterized queries in RSQLite 1.0.0 and later

### ISSUE THREAD

**Issue by danmbox** [rstats-db/RSQLite#76]
Queries of the type 
`dbGetQuery (bdconmem, "INSERT INTO ints VALUES (:n)", data.frame (n = 0:9))`
have suddenly stopped working in RSQLite 1.0.0 (the latest on CRAN), and there's no indication in the help or in the NEWS on how to use them.

In 1.0.9000 (whatever that version number means) I see you're further deprecating dbGetPreparedQuery (of which I wasn't previously aware) and recommending a two-step process (dbBind); how can we issue SQL queries in a single statement (or is that too convenient to have)?

**Comment by hadley** [comment]
That query should work again in the dev version, but put the data in a list instead of a data frame. And you'll need to manually loop - it's dangerous for a query to run an unspecified number of times. 

Also for that specific query, you can use `dbWriteTable()`

**Comment by hadley** [comment]
FWIW the reason `dbGetQuery (bdconmem, "INSERT INTO ints VALUES (:n)", data.frame (n = 0:9))` stopped working is that I didn't realise it was ever supposed to work :/

**Comment by danmbox** [comment]
For 1.0.0 what am I supposed to use -- dbGetPreparedQuery()?

And what looping are you talking about? Isn't there a version that accepts a vector and handles the opening and closing of result sets?

**Comment by danmbox** [comment]
More generally, what's the most efficient to query `SELECT * FROM recs WHERE m IN (:m) and n NOT IN (:n)` (binding vectors to m and n)? In the CRAN version and in the latest dev?

This doesn't seem very well documented, and you seem to imply that there's looping going under the hood.

**Comment by hadley** [comment]
For your initial query, I'd do:

```R
library(DBI)
con <- dbConnect(RSQLite::SQLite(), ":memory:")

# Create table
ints <- data.frame(n = integer())
dbWriteTable(con, "ints", ints)

# Insert a row at a time
df <- data.frame (n = 0:9)
rs <- dbSendQuery(con, "INSERT INTO ints VALUES (:n)")

for (i in 1:nrow(df)) {
  dbBind(rs, df[i, ])
}

dbReadTable(con, "ints")
```

For querying against a vector you have two options:

* Build the string up yourself, e.g. `paste(df$n, collapse = ",")`
* Upload a temporary table and do a semi join

Which is faster will depend on the size of the data
