### ISSUE TITLE
Cannot write tbl_df to SQLite database

### ISSUE THREAD

**Issue by rickyars** [rstats-db/RSQLite#82]
I currently cannot write `tbl_df` to SQLite databases:
```
> str(metric)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	23 obs. of  4 variables:
 $ Code       : chr  "AGR" "ALL" "BAS" "BSH" ...
 $ Name       : chr  "Agriculture" "Alligator" "Freshwater Fisheries" "Brown Shrimp" ...
 $ Description: chr  "Agriculture" "Alligator" "Freshwater Fisheries (represented by large mouth bass)" "Brown Shrimp" ...
 $ Units      : chr  "Suitability units" "Habitat units" "Habitat units" "Habitat units" ...
> dbWriteTable(db.sqlite, "Metric", metric, append=TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"SQLiteConnection", "character", "tbl_df"’
```
Converting my `tbl_df` via `as.data.frame()` works.

**Comment by hadley** [comment]
`setOldClass(c("tbl_df", "data.frame"))` should also fix the problem. That probably belongs in dplyr

**Comment by hadley** [comment]
Moved to https://github.com/hadley/dplyr/issues/969

**Comment by ajdamico** [comment]
does this solution belong in `haven` as well?  when i `read_dta` and try to put the result directly into a sqlite database without running your fix, i get the same error.  thanks!

**Comment by mugaruka** [comment]
I am facing the same problem when i haven::read_spss and try to put the result directly into a sqlite.

**Comment by krlmlr** [comment]
Could you please try the development version of `dplyr`, or use [the new `tibble` package](https://github.com/hadley/tibble) (not yet on CRAN)?

**Comment by siyang06** [comment]
**metric<-as.data.frame(metric)** should also solve this problem.
