### ISSUE TITLE
REGEXP with RSQLite?

### ISSUE THREAD

**Issue by jotsetung** [rstats-db/RSQLite#85]
dear develpers,
sorry, that's not really an issue but more a question... is there a way to use REGEXP with RSQLite? I didn't find a way to register a regexp function from R, but maybe I overlooked something...

thanks in advance!

**Comment by hadley** [comment]
See (e.g.) http://stackoverflow.com/questions/5071601/how-do-i-use-regex-in-a-sqlite-query

**Comment by ggrothendieck** [comment]
sqlite only has REGEXP if it's compiled in and I don't think RSQLite has done that.  On Windows,

```
> library(sqldf)
...
> sqldf("select 'a' regexp 'a'")
Loading required package: tcltk
Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such function: regexp

> packageVersion("RSQlite")
[1] ‘1.0.0’
```

**Comment by DavorJ** [comment]
A more helpful answer would be to explain how regexp.c from the SQLite source should be compiled such that it can be loaded into RSQLite. I have tried compiling it with GCC, and loading it in SQLite compiled with GCC -ldl, which works. But I was not able to load it with RSQLite, and I don't really know why. This is on Windows.

**Comment by krlmlr** [comment]
@DavorJ: Would you mind filing a new issue with a reference to this issue? Discussions in closed issues are difficult to track.
