### ISSUE TITLE
similar inherited method tbl_df issue for dbWriteTable

### ISSUE THREAD

**Issue by ajdamico** [rstats-db/RSQLite#86]
very similar to https://github.com/rstats-db/RSQLite/issues/82

i'm not sure fixing something in `dplyr` solves this problem, since neither `haven` nor `RSQLite` have `dplyr` as a dependency?  sorry if i'm overlooking something obvious

your workaround does solve the problem

example that breaks:

	library(haven)
	library(RSQLite)

	# # # only works if this gets run # # #
	# setOldClass( c( "tbl_df" , "data.frame" ) )

	db <- dbConnect( SQLite() , tempfile() )

	tf <- tempfile()

	download.file( "http://www.census.gov/housing/povmeas/spmresearch/spmresearch2013.sas7bdat" , tf , mode = 'wb' )

	x <- read_sas( tf )

	# this line breaks without the `setOldClass` line
	dbWriteTable( db , 'x' , x )

**Comment by krlmlr** [comment]
Thanks. I think this issue belongs in dplyr and/or haven, if we want to maintain the S4 signature of dbWriteTable. Working around this issue in DBI seems possible, but looks wrong.

**Comment by hadley** [comment]
@krlmlr agreed. This is just a challenge of working with both S3 and S4

**Comment by krlmlr** [comment]
For reference: The corresponding dplyr issue is https://github.com/hadley/dplyr/issues/969.
