### ISSUE TITLE
query about additional examples of functionality for the vignette 

### ISSUE THREAD

**Issue by nicholasjhorton** [rstats-db/RSQLite#87]
Is it possible to add two additional examples of functionality for the vignette:

(1) how to add to a table created using DBWriteTable()?

(2) how to index a table created using DBWriteTable() (after the call).

I suspect that many users would find this useful.
Just my $0.02,
Nick

**Comment by Kelsman28** [comment]
I don't think this questions was sent by me.  Strange.  Perhaps it was from
a group address from the seminar I took last week.

Julie

On Fri, Mar 27, 2015 at 11:02 AM, Nicholas Horton <notifications@github.com>
wrote:

> Is it possible to add two additional examples of functionality for the
> vignette:
>
> (1) how to add to a table created using DBWriteTable()?
>
> (2) how to index a table created using DBWriteTable() (after the call).
>
> I suspect that many users would find this useful.
> Just my $0.02,
> Nick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstats-db/RSQLite/issues/87>.
>



-- 
Graduate Student
Utah State University
Biology Department
Logan, Utah 84321
504-388-4153
julia.kelso@gmail.com

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
