### ISSUE TITLE
utf-8 issue

### ISSUE THREAD

**Issue by dafad** [rstats-db/RSQLite#88]
Could you please elaborate on [this](https://github.com/rstats-db/RSQLite/issues/69])? I'm struggling with Umlauts and I haven't found a way to fix it so far. What exactly did you mean?

**Comment by hadley** [comment]
Could you please provide a reproducible example?

**Comment by dafad** [comment]
Sure, see below. Like I said, I'm not 100% sure if it's the RSQLite driver. No problems with JDBC using Java, though. That's why I was asking for more information on the issue.

SQL dump (UTF-8):

    BEGIN TRANSACTION;
    CREATE TABLE `test` (
        `test`    TEXT
    );
    INSERT INTO `test` VALUES ('ä, ö, ü, ß');
    COMMIT;

R:

    library(DBI)
    con <- dbConnect(RSQLite::SQLite(), "test.sqlite")

    res <- dbSendQuery(con, "SELECT * FROM test")
    dbFetch(res) # prints: Ã¤, Ã¶, Ã¼, ÃŸ
    dbClearResult(res)

**Comment by dafad** [comment]
Looks like this was a Windows issue. [This](http://stackoverflow.com/a/22927566) helped:

    Sys.setlocale(category = "LC_ALL", locale = "English_United States.1252")

**Comment by hadley** [comment]
You shouldn't need to do that

**Comment by dafad** [comment]
Looks like this is an issue then. :-)

**Comment by krlmlr** [comment]
Confirmed on Windows: Encoding() returns "unknown".

**Comment by krlmlr** [comment]
Can't replicate anymore: Encoding() returns "unknown" for ASCII strings (as documented) but "UTF-8" for non-ASCII strings. Tested on Windows and Linux. Please comment if you're still seeing this problem.
