### ISSUE TITLE
UDFs

### ISSUE THREAD

**Issue by teucer** [rstats-db/RSQLite#92]
It could be really useful to be able to add UDFs to the database like SQLite.jl: https://github.com/quinnj/SQLite.jl#custom-scalar-functions

It is internally using https://www.sqlite.org/c3ref/create_function.html

I believe that this might be possible now that Rcpp is used.

**Comment by hadley** [comment]
This is currently out of scope because while Julia can relatively easily compile julia functions to C, R cannot.
