### ISSUE TITLE
Probably should upgrade to SQlite 3.8.10.2

### ISSUE THREAD

**Issue by talgalili** [rstats-db/RSQLite#96]
From the news: https://www.sqlite.org/news.html

> Yikes! Index corruption after a sequence of valid SQL statements!

> It has been many years since anything like this bug has snuck into an official SQLite release. But for the pasts seven months (version 3.8.7 through version **3.8.10.1**) if you do an INSERT into a carefully crafted schema in which there are two nested triggers that convert an index key value from TEXT to INTEGER and then back to TEXT again, the INTEGER value might get inserted as the index key instead of the correct TEXT, resulting in index corruption. This patch release adds a single line of code to fix the problem.

> If you do actually encounter this problem, running REINDEX on the damaged indexes will clear it.

**Comment by hadley** [comment]
Done in ce6b825a1371812fb4b64437a414796a0cdcfe88
