### ISSUE TITLE
text column values read as raw

### ISSUE THREAD

**Issue by dtenenba** [rstats-db/RSQLite#98]
Hi,

WIth the following sqlite3 database:

https://s3.amazonaws.com/rsqlite-text-problem/annotationhub.sqlite3

And the following code:

    library(DBI)
    con <- dbConnect(RSQLite::SQLite(), "annotationhub.sqlite3")
   dbGetQuery(con, "SELECT description FROM resources LIMIT 3");

The result is

             description
    1 46, 41, 53, 54, 41, 20, 44, 4e, 41, 20, 73, 65, 71, 75, 65, 6e, 63, 65, 20, 66, 6f, 72, 20, 41, 69, 6c, 75, 72, 6f, 70, 6f, 64, 61, 20, 6d, 65, 6c, 61, 6e, 6f, 6c, 65, 75, 63, 61
    2 46, 41, 53, 54, 41, 20, 44, 4e, 41, 20, 73, 65, 71, 75, 65, 6e, 63, 65, 20, 66, 6f, 72, 20, 41, 69, 6c, 75, 72, 6f, 70, 6f, 64, 61, 20, 6d, 65, 6c, 61, 6e, 6f, 6c, 65, 75, 63, 61
    3 46, 41, 53, 54, 41, 20, 44, 4e, 41, 20, 73, 65, 71, 75, 65, 6e, 63, 65, 20, 66, 6f, 72, 20, 41, 69, 6c, 75, 72, 6f, 70, 6f, 64, 61, 20, 6d, 65, 6c, 61, 6e, 6f, 6c, 65, 75, 63, 61

And yet 'description' is defined as a text file; in the sqlite3 shell:

    sqlite> .sch resources
    CREATE TABLE `resources` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `ah_id` varchar(255) NOT NULL, `title` varchar(255), `dataprovider` varchar(255), `species` varchar(255), `taxonomyid` integer, `genome` varchar(255), `description` text, `coordinate_1_based` boolean, `maintainer` varchar(255), `status_id` integer, `location_prefix_id` integer, `recipe_id` integer, `rdatadateadded` date, `rdatadateremoved` date, `record_id` integer, `preparerclass` varchar(255));

And the equivalent query in the shell returns text as expected:

    sqlite> select description from resources limit 3;
    FASTA DNA sequence for Ailuropoda melanoleuca
    FASTA DNA sequence for Ailuropoda melanoleuca
    FASTA DNA sequence for Ailuropoda melanoleuca

If it helps, I think I know what caused the database to get into the state where RSQLite is seeing the description field as raw, but I'm not sure why it's happening or whose fault it is.
The database was a MySQL database, and I first ran a (ruby) [Sequel](http://sequel.jeremyevans.net/) migration on it to change the type of the description column from varchar(255) to text; this should be equivalent to running an `alter table` query. Then I converted the MySQL database to sqlite, also using Sequel:

    sequel mysql://user:password@host/annotationhub -C sqlite://annotationhub.sqlite3

After doing this, I get the results above. 
I should note that I did not have this problem when the description column was a varchar(255).

If I reverse the migration (changing description's type from text back to varchar(255)) and re-convert the MySQL database to sqlite again, the code above works fine. 

One theory was that somehow there was non-ascii content in the database so it was read in as a raw vector instead of a character vector. But the content of the database has not changed, just the data type of one column. 

Using Sequel for migrations and converting the MySQL database to sqlite is part of an established workflow and I would prefer not to change it if at all possible.

Any ideas? Thanks.

**Comment by hadley** [comment]
SQLite doesn't type columns, it types individual values. I'd need a reproducible example to look into it in more details.

**Comment by dtenenba** [comment]
Thank you @hadley, the above example is reproducible. I provide a URL where you can get a database that demonstrates the problem, and code to demonstrate it.

I appreciate the explanation. What I don't understand is how (apparently) the same data comes through as raw when the underlying column type is text, but comes through as text when the underlying column type is varchar(255).

**Comment by hadley** [comment]
Oh sorry - I missed that. A reproducible example that is pure R code is preferable, but the raw db should be ok too.

But again, sqlite does not store the type of a column. Try running `SELECT typeof(description) FROM resources` to see what each cell is actually stored as.

**Comment by hadley** [comment]
The most likely source of the bug is the code that I use to try and guess the type of column I should use in R. Something must be making it think that the column contains a blob/raw, and so I pick that as the most flexible.

**Comment by dtenenba** [comment]
Aha, running `SELECT distinct typeof(description) ` returns `blob`. Therefore it seems this problem is perhaps upstream of RSQLite. Thanks.

**Comment by dtenenba** [comment]
Filed an issue in the appropriate place.
https://github.com/jeremyevans/sequel/issues/1071
